"""empty message

Revision ID: 075e5edce945
Revises: b9935427eabd
Create Date: 2024-07-08 15:57:06.064580

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '075e5edce945'
down_revision = 'b9935427eabd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('token', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'token')
    # ### end Alembic commands ###
