"""empty message

Revision ID: 6f4a4c9eacab
Revises: 964227dd1bbd
Create Date: 2024-07-08 13:21:53.255339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f4a4c9eacab'
down_revision = '964227dd1bbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('name', sa.String(length=80), nullable=False))
    op.add_column('Users', sa.Column('password', sa.String(length=80), nullable=False))
    op.add_column('Users', sa.Column('email', sa.String(length=80), nullable=False))
    op.drop_constraint('Users_Email_key', 'Users', type_='unique')
    op.create_unique_constraint(None, 'Users', ['email'])
    op.drop_column('Users', 'Name')
    op.drop_column('Users', 'Password')
    op.drop_column('Users', 'Email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('Email', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('Users', sa.Column('Password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('Users', sa.Column('Name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Users', type_='unique')
    op.create_unique_constraint('Users_Email_key', 'Users', ['Email'])
    op.drop_column('Users', 'email')
    op.drop_column('Users', 'password')
    op.drop_column('Users', 'name')
    # ### end Alembic commands ###
