"""empty message

Revision ID: b9935427eabd
Revises: 6f4a4c9eacab
Create Date: 2024-07-08 14:24:11.349310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9935427eabd'
down_revision = '6f4a4c9eacab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Books',
    sa.Column('ISBN', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('author', sa.String(length=80), nullable=False),
    sa.Column('copies_available', sa.Integer(), nullable=False),
    sa.Column('copies_total', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ISBN')
    )
    op.create_table('Borrowed_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_ISBN', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['book_ISBN'], ['Books.ISBN'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Borrowed_books')
    op.drop_table('Books')
    # ### end Alembic commands ###
