"""empty message

Revision ID: bbc525d6d902
Revises: 
Create Date: 2024-07-08 11:02:50.254716

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bbc525d6d902'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Test',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('data1', sa.String(), nullable=True),
                    sa.Column('data2', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Test')
    # ### end Alembic commands ###
